#!/bin/bash
# Script pour aider à résoudre le problème de clé SSH déjà utilisée

echo "🔍 Diagnostic de la clé SSH..."
echo ""
echo "Votre clé publique SSH :"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
cat ~/.ssh/id_ed25519.pub
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "❌ Cette clé est déjà utilisée quelque part sur GitHub."
echo ""
echo "📋 Solutions possibles :"
echo ""
echo "Option 1 : Retirer la Deploy Key et ajouter comme SSH Key"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Allez sur : https://github.com/ubntexd/crypto_portfolio_guard/settings/keys"
echo "2. Dans 'Deploy keys', trouvez et supprimez cette clé"
echo "3. Allez sur : https://github.com/settings/keys"
echo "4. Cliquez 'New SSH key' et ajoutez la clé ci-dessus"
echo ""
echo "Option 2 : Générer une nouvelle clé SSH (Recommandé)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Exécutez cette commande pour générer une nouvelle clé :"
echo ""
echo "  ssh-keygen -t ed25519 -C 'andoh.ezan1@gmail.com' -f ~/.ssh/id_ed25519_crypto_portfolio"
echo ""
echo "Puis ajoutez la nouvelle clé (~/.ssh/id_ed25519_crypto_portfolio.pub) à :"
echo "  https://github.com/settings/keys"
echo ""
echo "Et configurez Git pour utiliser cette clé :"
echo "  git config core.sshCommand 'ssh -i ~/.ssh/id_ed25519_crypto_portfolio'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
